"""Terrain fixtures for test_footprint_plane, from diag-run4's maps (README.md)."""

import json, math, sys
import numpy as np

RES = 0.2
CORRIDOR = 1.5
BAND_BELOW, BAND_ABOVE = 1.0, 0.3


def path(data, robot, first, last):
    sol = json.load(open(f"{data}/{robot}/graph_solution.json"))["solution"]
    rid = "robot_" + robot[1]
    poses = {
        q["keyframe_id"]["seq"]: np.array(q["T_component_keyframe"])
        for q in sol["poses"]
        if q["keyframe_id"]["robot_id"] == rid
    }
    return np.array([poses[s][:3, 3] for s in range(first, last + 1)])


def seg_dist(p, a, b):
    d = b - a
    t = np.clip(((p - a) @ d) / max(d @ d, 1e-12), 0, 1)
    return np.linalg.norm(p - (a + t[:, None] * d), axis=1)


def write(out, title, points, keyframes):
    xy = keyframes[:, :2]
    lo, hi = xy.min(0) - CORRIDOR - RES, xy.max(0) + CORRIDOR + RES
    p = points[
        (points[:, 0] > lo[0])
        & (points[:, 0] < hi[0])
        & (points[:, 1] > lo[1])
        & (points[:, 1] < hi[1])
    ]
    dist = np.full(len(p), np.inf)
    nearest_z = np.zeros(len(p))
    for a, b, za, zb in zip(xy[:-1], xy[1:], keyframes[:-1, 2], keyframes[1:, 2]):
        d = seg_dist(p[:, :2], a, b)
        closer = d < dist
        dist[closer] = d[closer]
        nearest_z[closer] = 0.5 * (za + zb)
    keep = (
        (dist <= CORRIDOR)
        & (p[:, 2] > nearest_z - BAND_BELOW)
        & (p[:, 2] < nearest_z + BAND_ABOVE)
    )
    top = {}
    for x, y, z in p[keep, :3]:
        c = (math.floor(x / RES), math.floor(y / RES))
        if z > top.get(c, -1e9):
            top[c] = z
    with open(out, "w") as f:
        f.write(f"# {title}\n")
        f.write("# Generated by make_terrain_fixtures.py; see README.md.\n")
        f.write(f"resolution {RES}\n")
        for x, y, z in keyframes:
            f.write(f"pose {x:.3f} {y:.3f} {z:.3f}\n")
        for (ix, iy), z in sorted(top.items()):
            f.write(f"cell {ix} {iy} {z:.3f}\n")
    print(out, len(keyframes), len(top))


data, outdir = sys.argv[1], sys.argv[2]
r2 = path(data, "r2", 612, 629)
r0 = path(data, "r0", 1285, 1328)
write(
    f"{outdir}/rock_field_preplan.txt",
    "robot_2's map of the rock field before its 1790306219 plan "
    "(submaps <= keyframe 622), keyframes 612-629",
    np.load(f"{data}/r2_rocks_preplan.npy"),
    r2,
)
write(
    f"{outdir}/rock_field_now.txt",
    "robot_2's map of the rock field after the event, keyframes 612-629",
    np.load(f"{data}/r2_rocks.npy"),
    r2,
)
write(
    f"{outdir}/subt_ramp.txt",
    "robot_0's map of the 16 degree SubT ramp, keyframes 1285-1328",
    np.load(f"{data}/r0_ramp.npy"),
    r0,
)
