grid_map_topic: /R1/elevation_mapping/elevation_map

grid_map_visualizations:
  - name: elevation_cloud
    type: point_cloud
    params:
     layer: elevation
    # Compute Surface normals
  - name: surface_normals
    type: point_cloud
    params:
      layer: normal_vectors_