string component_id
uint64 epoch
uint64 graph_revision
string geometry_revision
builtin_interfaces/Time source_stamp
geometry_msgs/Point[] samples
geometry_msgs/Vector3 body_size
bool stop_at_unknown
---
uint8 OK=0
uint8 STALE=1
uint8 UNAVAILABLE=2
uint8 status
string component_id
uint64 epoch
uint64 graph_revision
string geometry_revision
uint8 UNKNOWN=0
uint8 FREE=1
uint8 OCCUPIED=2
uint8[] occupancy
float64[] ground_z
float64[] roughness
float64[] clearance
bool[] step
bool[] drop
string detail
