string mission_id
string route_id
string component_id
uint64 graph_revision
uint64 map_revision
uint64 map_epoch
uint64 mapping_graph_revision
string geometry_revision
builtin_interfaces/Time map_source_stamp
---
uint8 SUCCEEDED=0
uint8 UNREACHABLE=1
uint8 STALE_REVISION=2
uint8 UNSUPPORTED_OBJECTIVE=3
uint8 BLOCKED=4
uint8 status
string component_id
uint64 graph_revision
uint64 map_revision
uint64 map_epoch
uint64 mapping_graph_revision
string geometry_revision
builtin_interfaces/Time map_source_stamp
geometry_msgs/Pose[] path
bool partial
bool indexed_map_validated
string reason
