#!/usr/bin/env python3
"""Emit the Bistro MGG exploration experiment.

Four foot-bots explore the Bistro street scene under the MGG planner. Unlike
the Swarm-SLAM demos in argos3-examples that this borrows the scene from, the
robots have no route: they stand still until the planner sends them somewhere.

    tools/make_bistro_mgg.py [--examples-root DIR] [--robots N] [--gui]

Writes ros2/src/mgg_argos/experiments/bistro_mgg.argos.

Why generated rather than written by hand: the scene is 4346 collision boxes
and 60-odd street lamps, inlined from two .inc files, which is why the result
is a 640 kB file nobody should edit. Everything here that is not the scene is
small, and lives in this script so it can be re-derived when the scene moves.

The scene comes from argos3-examples, whose bistro_footbot_*.argos are
generated by experiments/bistro_exploration/tools/make_footbot_slam.py. That
file is the reference for the parts reproduced here: the prop sits 0.3 m low so
the rendered street lands on the z=0 floor the robots drive on, the collision
include was voxelised with the same transform, and the lighting is a night
street (a residual twilight sky, no sun, and the lamps carrying the scene) with
the camera exposure opened nine stops to match. Those four numbers move
together; changing one alone only makes the image wrong.

Asset paths are emitted absolute. The originals are relative to the
argos3-examples root because that is where argos3 is run from there; this
experiment is run from wherever the demo script puts it.
"""
import argparse
import math
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

# The closed street tour from make_footbot_slam.py, used here only as a source
# of known-drivable start positions. It was planned by BFS over a 0.5 m
# occupancy grid of the actual glTF triangles with 0.85 m clearance, and
# verified to keep 0.30 m from every collision box, which is a guarantee no
# hand-picked coordinate would carry. The planner decides everything after the
# first metre.
TOUR = [(-10.75, 8.25), (-7.75, -12.25), (-5.75, -13.25),
        (14.25, -15.75), (40.25, -25.75), (20.25, -18.75),
        (11.25, -14.75), (-3.75, -14.75), (-9.25, -1.75)]

# Night lighting, copied from make_footbot_slam.py. See the note above.
SKY_LUX = 8.0
SUN_LUX = 0.0
SKY_COLOR = "0.045,0.055,0.085"
APERTURE, SHUTTER, ISO = 2.0, 0.02, 400.0

# 10 ticks/s, as in the small-arena demo: the planner works off /clock and the
# bridge is lockstep, so a faster tick buys nothing but render cost. The
# Swarm-SLAM variants use 100 because they need IMU-rate physics.
TICKS_PER_SECOND = 10
# One scan every five ticks, i.e. 2 Hz. A scan is four face renders, so four
# robots scanning every tick would be 160 renders a second and the run would be
# GPU-bound rather than planner-bound. The planner replans far slower than 2 Hz
# anyway.
LIDAR_DIVIDER = 5
# The VLP-16's own 0.2 degrees. Coarsening this was tried and reverted: at 24
# rings, 1 degree leaves the rays 0.17 m apart at 10 m, wider than the 0.15 m
# map voxel, so the scan stops carving a connected volume and every edge comes
# back "occupied" with no vertices at all. It was coarsened to chase a 100% CPU
# reading that turned out to be the planner's ordinary steady state - the same
# figure appears in the single-robot run that works - so the change fixed
# nothing and broke the map. A scan is 43200 points here, which the 20-core
# host absorbs.
LIDAR_HORIZONTAL_RESOLUTION = 0.2


def strip_comments(text):
    """Removes XML comments from inlined scene geometry.

    The comments record how the voxeliser and the lamp extractor were invoked,
    which this file's own header already credits, and they carry option names
    like "--height". A double hyphen is illegal inside an XML comment, so
    keeping them makes the output unreadable to any conforming parser. ARGoS
    uses tinyxml, which accepts it, which is why the upstream Bistro
    experiments have shipped that way without anyone noticing.
    """
    return re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)


def parse_boxes(text):
    """(cx, cy, half_x, half_y) for every collision box, in the xy plane."""
    out = []
    for match in re.finditer(
            r'<box[^>]*size="([^"]+)"[^>]*>\s*<body position="([^"]+)"', text):
        sx, sy, _ = (float(v) for v in match.group(1).split(","))
        cx, cy, _ = (float(v) for v in match.group(2).split(","))
        out.append((cx, cy, sx * 0.5, sy * 0.5))
    return out


def clearance(x, y, boxes):
    """Distance from (x, y) to the nearest collision box footprint."""
    best = float("inf")
    for cx, cy, hx, hy in boxes:
        dx = max(abs(x - cx) - hx, 0.0)
        dy = max(abs(y - cy) - hy, 0.0)
        best = min(best, math.hypot(dx, dy))
        if best == 0.0:
            break
    return best


def start_poses(n, boxes, corner_clearance=3.0, spacing=1.0,
                box_clearance=1.5, bootstrap_distance=6.0):
    """n start positions spread around the tour, each facing along it.

    Spread by distance in space, not by distance along the route. The Bistro
    tour is a there-and-back: it runs out along the street and returns down
    nearly the same one, so points a quarter of the loop apart can be a metre
    apart on the ground. Arc-length spacing put two robots 0.9 m from each
    other, which is not four robots exploring a street, it is two pairs.

    So: sample the whole tour finely, drop everything near a corner, then take
    the n points that are farthest apart by greedy farthest-point selection.

    Candidates also have to stand clear of the collision geometry, which
    includes 650 proxies for the raised pavement. The Bistro kerb is about
    0.16 m and the planner's collision box rides from 0.2 m up, so a kerb
    inside the box footprint is a genuine obstacle and the planner is right to
    refuse it - but a robot parked against one has that obstacle at its graph
    root, and then every edge out of the root is rejected and it never moves.
    Measured: a robot with geometry 0.43 m away at kerb height produced 2054
    rejected edges and no vertices, while robots whose nearest such geometry
    was 1.35 m away produced 96 to 148 vertices.

    The tour is drivable, so its waypoints are clear of the boxes; they are not
    necessarily 1.5 m clear, because a route only has to fit a robot through.

    The clearance is required along the whole nudge, not just at the start.
    The demo drives each robot a few metres before asking the planner for
    anything, so where that nudge ends is where the first graph is rooted, and
    a start that is clear but points at a kerb five metres away fails in
    exactly the same way as a start that is against one. bootstrap_distance
    has to cover what tools/argos_bootstrap.py drives.
    """
    candidates = []
    for i in range(len(TOUR)):
        a, b = TOUR[i], TOUR[(i + 1) % len(TOUR)]
        length = math.hypot(b[0] - a[0], b[1] - a[1])
        if length < 2 * corner_clearance:
            continue
        steps = int(length / spacing)
        yaw = math.degrees(math.atan2(b[1] - a[1], b[0] - a[0]))
        for step in range(steps + 1):
            travelled = step * spacing
            if (travelled < corner_clearance or
                    travelled > length - corner_clearance):
                continue
            t = travelled / length
            x = round(a[0] + t * (b[0] - a[0]), 2)
            y = round(a[1] + t * (b[1] - a[1]), 2)
            heading = math.radians(yaw)
            ahead = [(x + d * math.cos(heading), y + d * math.sin(heading))
                     for d in [0.0] + [0.5 * k for k in
                                       range(1, int(bootstrap_distance / 0.5) + 1)]]
            if any(clearance(px, py, boxes) < box_clearance for px, py in ahead):
                continue
            candidates.append((x, y, yaw))
    total = sum(math.hypot(TOUR[(i + 1) % len(TOUR)][0] - TOUR[i][0],
                           TOUR[(i + 1) % len(TOUR)][1] - TOUR[i][1])
                for i in range(len(TOUR)))
    if len(candidates) < n:
        raise SystemExit(
            f"only {len(candidates)} start positions have {box_clearance} m of "
            f"clearance for {n} robots; lower box_clearance or corner_clearance")

    # Greedy farthest-point: start from the first candidate, then repeatedly
    # take whichever is farthest from everything picked so far.
    chosen = [candidates[0]]
    while len(chosen) < n:
        best, best_distance = None, -1.0
        for candidate in candidates:
            nearest = min(math.hypot(candidate[0] - c[0], candidate[1] - c[1])
                          for c in chosen)
            if nearest > best_distance:
                best, best_distance = candidate, nearest
        chosen.append(best)
    return chosen, total


def controller(i):
    return f"""
    <mgg_footbot library="libmgg_footbot.so" id="mgg{i}">
      <actuators>
        <differential_steering implementation="default" />
      </actuators>
      <sensors>
        <!-- Ground truth, used only to drive the wheels. The planner never
             sees it; it gets the drifting estimate below. -->
        <positioning implementation="default" />
        <odometry implementation="drift"
                  position_drift="0.02" orientation_drift="0.01" />
        <imu implementation="default"
             gyro_noise_std_dev="0.002" accel_noise_std_dev="0.02"
             gyro_bias_walk_std_dev="0.0002" accel_bias_walk_std_dev="0.002" />
        <!-- Tilted down to -30 rather than the VLP-16's own -15: level at
             this height the lowest ray only reaches the street 1.5 m out, the
             ground arrives as a few thin rings and never near the robot, and
             ground projection then finds nothing to stand on. The faces are
             512x352 because 4 faces of that aspect see +/-34.5 degrees, which
             is what covers a 45 degree band. -->
        <photorealistic_lidar implementation="default" medium="pr"
                              anchor="origin" position="0,0,0.25"
                              vertical_fov="-30,15" rings="24"
                              face_resolution="512,352" max_range="20"
                              horizontal_resolution="{LIDAR_HORIZONTAL_RESOLUTION}"
                              framerate_divider="{LIDAR_DIVIDER}" />
      </sensors>
      <params robot_id="r{i}" cruise_speed="50" turn_speed="20"
              turn_gain="60" align_threshold="35"
              waypoint_tolerance="0.4" goal_tolerance="0.5" />
    </mgg_footbot>"""


def robot(i, pose):
    x, y, yaw = pose
    return f"""    <foot-bot id="fb{i}">
      <body position="{x},{y},0" orientation="{yaw:.1f},0,0" />
      <controller config="mgg{i}" />
    </foot-bot>"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--examples-root", default="../argos3-examples",
                        help="argos3-examples checkout holding the Bistro scene")
    parser.add_argument("--robots", type=int, default=4)
    parser.add_argument("--gui", action="store_true",
                        help="add a windowed viewer with per-robot insets")
    parser.add_argument("--socket", default="/tmp/mgg_argos.sock")
    parser.add_argument("--length", type=int, default=0,
                        help="seconds; 0 runs until interrupted")
    parser.add_argument("-o", "--output", default=None)
    args = parser.parse_args()

    root = pathlib.Path(args.examples_root).expanduser().resolve()
    scene = root / "experiments" / "bistro_exploration"
    assets = scene / "assets"
    # The collision geometry comes from the voxeliser's .inc when it is
    # present, and otherwise straight out of one of the generated Bistro
    # experiments, which have it inlined. The .inc is a build artefact and is
    # not checked in; the .argos files are. Either way the boxes are identical,
    # since the .argos was made by inlining the .inc.
    collision = assets / "bistro_collision_footbot.inc"
    if collision.exists():
        boxes = collision.read_text()
        boxes = boxes[boxes.index("<box"):]
        boxes = boxes[:boxes.rindex("</box>") + len("</box>")]
    else:
        source = next((scene / name for name in
                       ("bistro_footbot_live.argos", "bistro_footbot_slam.argos",
                        "bistro_footbot_viewer.argos")
                       if (scene / name).exists()), None)
        if source is None:
            print(f"error: no Bistro collision geometry under {scene}.\n"
                  f"Expected either assets/bistro_collision_footbot.inc or one "
                  f"of the generated bistro_footbot_*.argos files. Run "
                  f"{scene}/fetch_assets.sh and "
                  f"{scene}/tools/make_footbot_slam.py first.", file=sys.stderr)
            return 1
        text = source.read_text()
        # Everything between the last robot and the end of the arena.
        start = text.index("<box", text.index("</foot-bot>"))
        boxes = text[start:text.index("</arena>", start)]
        boxes = boxes[:boxes.rindex("</box>") + len("</box>")]
        print(f"  (collision geometry taken from {source.name})")
    boxes = strip_comments(boxes)
    boxes = "\n".join("    " + line.strip() for line in boxes.splitlines()
                      if line.strip())
    lamps = strip_comments((assets / "bistro_lamps.inc").read_text())
    lamps = "\n".join("        " + line.strip()
                      for line in lamps.splitlines() if line.strip())

    poses, total = start_poses(args.robots, parse_boxes(boxes))
    controllers = "".join(controller(i) for i in range(args.robots))
    robots = "\n".join(robot(i, p) for i, p in enumerate(poses))
    robot_ids = ",".join(f"fb{i}" for i in range(args.robots))

    if args.gui:
        insets = ",".join(f"fb{i}" for i in range(args.robots))
        visualization = f"""  <visualization>
    <!-- Street level on purpose: Bistro is a street-level game asset with
         hollow, single-sided roofs, so an aerial viewpoint sees through the
         buildings. The planner's paths and graphs are drawn into this window
         and nowhere else - no sensor can see them. -->
    <filament medium="pr" resolution="1280,720" speed="1"
              near="0.3" far="400"
              position="-7.25,-12.75,3.0" look_at="-9.5,0.5,1.2"
              inset_camera="{insets}" inset_size="0.24" />
  </visualization>"""
    else:
        visualization = ("  <!-- Headless. Re-run the generator with the gui\n"
                     "       option for a window. -->")

    out = f"""<?xml version="1.0" ?>
<argos-configuration>

  <!-- GENERATED by tools/make_bistro_mgg.py - do not edit by hand.

      {args.robots} foot-bots exploring the Bistro street under the MGG planner.
      They start spread around a {total:.0f} m street loop and have no route:
      each stands still until the planner sends it somewhere.

      Start the ROS 2 side first - it creates the socket, the simulator
      connects to it:

          ros2 launch mgg_argos bistro.launch.py

      then, with ARGOS_PLUGIN_PATH covering the mgg_argos plugin build:

          argos3 -c bistro_mgg.argos

      or run tools/run_argos_demo.sh with the bistro option, which
      does both.
  -->

  <framework>
    <system threads="0" />
    <experiment length="{args.length}" ticks_per_second="{TICKS_PER_SECOND}"
                random_seed="7" />
  </framework>

  <controllers>{controllers}
  </controllers>

  <!-- Bidirectional: observations out, planner commands back, in lockstep.
       draw_medium makes it also draw each robot's path and graph into the
       photorealism overlay, which only the viewer above can see. -->
  <loop_functions library="libmgg_bridge.so" label="mgg_bridge"
                  socket="{args.socket}" robots="{robot_ids}"
                  send_ground_truth="true" draw_medium="pr" />

  <arena size="200,210,70" center="24,-4,25">
{robots}

{boxes}
  </arena>

  <physics_engines>
    <jolt id="jolt" iterations="10" threads="1">
      <floor height="0" />
      <gravity g="9.81" />
    </jolt>
  </physics_engines>

  <media>
    <!-- hide_prefix: collision proxies are solid to physics, never drawn. The
         prop sits 0.3 m low so the rendered street surface lands at the z=0
         floor the foot-bots drive on; the collision include was voxelised with
         the same transform. -->
    <photorealism id="pr" backend="vulkan" hide_prefix="obs_" draw_floor="false">
      <environment ibl="{assets}/san_giuseppe_ibl.ktx"
                   intensity="{SKY_LUX:g}" />
      <skybox color="{SKY_COLOR}" />
      <sun direction="0.85,0.35,-0.22" intensity="{SUN_LUX:g}"
           cast_shadows="false" />
      <exposure aperture="{APERTURE:g}" shutter_speed="{SHUTTER:g}"
                sensitivity="{ISO:g}" />
      <lights>
{lamps}
      </lights>
      <scenery>
        <prop model="{assets}/bistro_exterior.glb"
              position="0,0,-0.3" orientation="0,0,90" scale="1.0" />
      </scenery>
    </photorealism>
  </media>

{visualization}

</argos-configuration>
"""
    dest = (pathlib.Path(args.output) if args.output else
            pathlib.Path(__file__).resolve().parent.parent /
            "ros2" / "src" / "mgg_argos" / "experiments" / "bistro_mgg.argos")
    dest.parent.mkdir(parents=True, exist_ok=True)
    # Parse before writing. A 630 kB generated file that ARGoS rejects on
    # startup is a slow thing to debug, and ARGoS's parser is lenient enough
    # that "it loaded" is not evidence the file is well formed.
    try:
        ET.fromstring(out)
    except ET.ParseError as error:
        print(f"error: generated XML is malformed: {error}", file=sys.stderr)
        return 1

    dest.write_text(out)
    print(f"wrote {dest}")
    print(f"  {args.robots} robots, {boxes.count('<box')} collision boxes, "
          f"{total:.0f} m loop")
    closest = min(
        (math.hypot(a[0] - b[0], a[1] - b[1]), i, j)
        for i, a in enumerate(poses) for j, b in enumerate(poses) if i < j)
    for i, (x, y, yaw) in enumerate(poses):
        print(f"  r{i} starts at ({x}, {y}) facing {yaw:.0f} deg")
    print(f"  closest pair: r{closest[1]} and r{closest[2]}, "
          f"{closest[0]:.1f} m apart")
    box_list = parse_boxes(boxes)
    worst = (float("inf"), -1)
    for i, (x, y, yaw) in enumerate(poses):
        heading = math.radians(yaw)
        for d in range(0, 13):
            px, py = x + 0.5 * d * math.cos(heading), y + 0.5 * d * math.sin(heading)
            worst = min(worst, (clearance(px, py, box_list), i))
    print(f"  tightest point along any nudge: r{worst[1]}, "
          f"{worst[0]:.2f} m from an obstacle")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
